---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# crimtools

<!-- badges: start -->
<!-- badges: end -->

The goal of crimtools is to ...

## Installation

You can install the development version of crimtools from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("gmcirco/crimtools")
```

## Kernel Density Estimation

The `crimtools` package is intended to be used with simple features from the `sf`
package (see [this link](https://r-spatial.github.io/sf/articles/sf1.html) for a more in-depth description of simple features in R).

```{r example}
library(crimtools)
library(sf)

data("newhaven")
data("nh_hom")

kde_out <- kernel_density(x = nh_hom, region = newhaven)
```

```{r cars}
library(ggplot2)

ggplot(kde_out) +
  geom_tile(aes(x = X, y = Y, fill = density)) +
  coord_equal() +
  scale_fill_viridis_c(option = "magma") +
  theme_void()

```
